{"name": "Система возвращает ошибку, если неправильно указать логин", "status": "passed", "steps": [{"name": "Логинимся", "status": "passed", "parameters": [{"name": "login", "value": "'invalid_login'"}, {"name": "password", "value": "'valid_password'"}], "start": 1739802089594, "stop": 1739802089818}], "start": 1739802089593, "stop": 1739802089819, "uuid": "1f15c89b-e16d-4417-9711-6aaf16835686", "historyId": "098c31939dfc5a0448c18624846e2e61", "testCaseId": "098c31939dfc5a0448c18624846e2e61", "fullName": "tests.tests_login.TestLogin#test_login_courier_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "tests_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-5IUKQF9"}, {"name": "thread", "value": "8952-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_login"}]}